### ISSUE TITLE
Configurable Pod Affinities

### ISSUE THREAD

**Issue by PatTheSilent** [letsbuilders/jsonnet-libs#66]
We'd like to be able to easily configure pod affinities. We'd also like to prevent multiple Pods of the same deployment get scheduled onto the same node.

TODO:
* add support for configuring pod affinities
* add a default anti-affinity config that will suggest the scheduler not to put pods of the same deployment on one node.

**Comment by YuriiBudnyi** [comment]
The issue has been resolved. Commit 613ae1d663adba406f828f692d02e953a570cbef
